// <auto-generated />
namespace FestMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FestivalManagers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FestivalManagers));
        
        string IMigrationMetadata.Id
        {
            get { return "201702131127483_FestivalManagers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
