// <auto-generated />
namespace WebAPI_SimpleLogin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201709040903498_removeUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
